import { Property } from './supabase'

export const dummyProperties: Property[] = [
  {
    id: '1',
    name: 'Kost Exclusive Simpang Lima',
    type: 'kost',
    location: 'Simpang Lima, Semarang',
    price_monthly: 1500000,
    price_daily: 100000,
    assets_value: 450000000,
    status: 'available',
    images: [],
  },
  {
    id: '2',
    name: 'Apartment Paragon City',
    type: 'apartment',
    location: 'Paragon Mall, Semarang',
    price_monthly: 5000000,
    price_daily: 400000,
    assets_value: 1500000000,
    status: 'available',
    images: [],
  },
  {
    id: '3',
    name: 'Villa Bandungan Highland',
    type: 'villa',
    location: 'Bandungan, Semarang',
    price_monthly: 9000000,
    price_daily: 850000,
    assets_value: 3000000000,
    status: 'available',
    images: [],
  },
  {
    id: '4',
    name: 'Homestay Lawang Sewu Heritage',
    type: 'homestay',
    location: 'Lawang Sewu, Semarang',
    price_monthly: 2800000,
    price_daily: 220000,
    assets_value: 700000000,
    status: 'available',
    images: [],
  },
  {
    id: '5',
    name: 'Kost Pemuda Street',
    type: 'kost',
    location: 'Jl. Pemuda, Semarang',
    price_monthly: 1200000,
    price_daily: 80000,
    assets_value: 350000000,
    status: 'available',
    images: [],
  },
  {
    id: '6',
    name: 'Apartment Ciputra Semarang',
    type: 'apartment',
    location: 'Ciputra Mall, Semarang',
    price_monthly: 4200000,
    price_daily: 320000,
    assets_value: 1200000000,
    status: 'available',
    images: [],
  },
  {
    id: '7',
    name: 'Villa Ambarawa View',
    type: 'villa',
    location: 'Ambarawa, Semarang',
    price_monthly: 7500000,
    price_daily: 700000,
    assets_value: 2500000000,
    status: 'maintenance',
    images: [],
  },
  {
    id: '8',
    name: 'Homestay Kota Lama',
    type: 'homestay',
    location: 'Kota Lama, Semarang',
    price_monthly: 2500000,
    price_daily: 200000,
    assets_value: 650000000,
    status: 'available',
    images: [],
  },
  {
    id: '9',
    name: 'Kost Pandanaran Premium',
    type: 'kost',
    location: 'Jl. Pandanaran, Semarang',
    price_monthly: 1800000,
    price_daily: 120000,
    assets_value: 500000000,
    status: 'available',
    images: [],
  },
  {
    id: '10',
    name: 'Apartment Marina Bay',
    type: 'apartment',
    location: 'Marina, Semarang',
    price_monthly: 6000000,
    price_daily: 500000,
    assets_value: 1800000000,
    status: 'available',
    images: [],
  },
  {
    id: '11',
    name: 'Villa Ungaran Hills',
    type: 'villa',
    location: 'Ungaran, Semarang',
    price_monthly: 8500000,
    price_daily: 800000,
    assets_value: 2800000000,
    status: 'available',
    images: [],
  },
  {
    id: '12',
    name: 'Homestay Tugu Muda',
    type: 'homestay',
    location: 'Tugu Muda, Semarang',
    price_monthly: 2200000,
    price_daily: 180000,
    assets_value: 600000000,
    status: 'available',
    images: [],
  },
  {
    id: '13',
    name: 'Kost Gajah Mada',
    type: 'kost',
    location: 'Jl. Gajah Mada, Semarang',
    price_monthly: 1400000,
    price_daily: 95000,
    assets_value: 400000000,
    status: 'available',
    images: [],
  },
  {
    id: '14',
    name: 'Apartment Puri Anjasmoro',
    type: 'apartment',
    location: 'Anjasmoro, Semarang',
    price_monthly: 3800000,
    price_daily: 300000,
    assets_value: 1100000000,
    status: 'available',
    images: [],
  },
  {
    id: '15',
    name: 'Villa Bawen Retreat',
    type: 'villa',
    location: 'Bawen, Semarang',
    price_monthly: 7000000,
    price_daily: 650000,
    assets_value: 2300000000,
    status: 'available',
    images: [],
  },
]
